name: Copyright
description: Checks whether the correct copyright headers are present.

inputs:
  # Basic inputs
  name:
    description: The name in the phrase "the $name Authors".
    required: false
    default: ""
  license:
    description: The SPDX license expression.
    required: false
    default: Apache-2.0 OR MIT
  globs:
    description: The files to include and exclude.
    required: false
    default: -g '*.rs'
  # Advanced inputs
  config:
    # Expected input JSON format:
    # [
    #   {
    #     "name":    "Cool",
    #     "license": "Apache-2.0 OR MIT",
    #     "globs":   "-g '*.rs' -g '!other'"
    #   },
    #   {
    #     "name":    "Cool",
    #     "license": "BSD",
    #     "globs":   "-g 'other/**/*.rs'"
    #   }
    # ]
    description: Advanced configuration in a single JSON array, overrides basic inputs.
    required: false
    default: ""

# TODO: Add support for the advanced config -- but potentially consider keeping the simpler inputs too just so the action is more fancy.

runs:
  using: composite
  steps:
    - name: Install ripgrep
      uses: xStrom/ci-test/install@main

    - name: Check copyright headers
      shell: bash
      env:
        ARG_NAME: ${{ inputs.name }}
        ARG_LICENSE: ${{ inputs.license }}
        ARG_GLOBS: ${{ inputs.globs }}
        ARG_CONFIG: ${{ inputs.config }}
      run: |
        # Check copyright headers
        escape_for_regex() {
          echo "$1" | perl -pe 's/([.\^\$*+?()[\]{}\\])/\\$1/g'
        }

        check_headers() {
          name_regex=$(escape_for_regex "$1")
          spdx_expression_regex=$(escape_for_regex "$2")
          header_regex="^// Copyright (19|20)[\d]{2} (.+ and )?the $name_regex Authors( and .+)?\$\n^// SPDX-License-Identifier: $spdx_expression_regex\$\n\n"
          echo "Checking headers with regex: $header_regex"
          echo "In the following locations: $3"

          set +e
          output=$(rg "$header_regex" --files-without-match --multiline $3 .)
          set -e

          if [ -n "$output" ]; then
            echo -e "The following files lack the correct copyright header:\n"
            echo $output
            echo -e "\n\nPlease add the following header:\n"
            echo "// Copyright $(date +%Y) the $1 Authors"
            echo "// SPDX-License-Identifier: $2"
            echo -e "\n... rest of the file ...\n"
            exit 1
          fi

          echo "All files have correct copyright headers."
        }

        # TODO: Confirm that jq and every other used app exists in all scripts

        if [ -n "$ARG_CONFIG" ]; then
          echo "$ARG_CONFIG" | jq -c '.[]' | while IFS= read -r cfg; do
            name=$(echo "$cfg" | jq -r '.name')
            license=$(echo "$cfg" | jq -r '.license')
            globs=$(echo "$cfg" | jq -r '.globs')
            check_headers "$name" "$license" "$globs"
          done
        else
          check_headers "$ARG_NAME" "$ARG_LICENSE" "$ARG_GLOBS"
        fi
