name: Copyright
description: Checks whether the correct copyright headers are present.

inputs:
  project-name:
    description: The name in the phrase "the $name Authors".
    required: true
  license:
    description: The SPDX license expression.
    required: false
    default: Apache-2.0 OR MIT
  globs:
    description: The files to include and exclude.
    required: false
    default: -g "*.rs"

runs:
  using: composite
  steps:
    - name: Install ripgrep
      uses: xStrom/ci-test/install@main

    - name: Check copyright headers
      shell: bash
      run: |
        escape_for_regex() {
          echo "$1" | perl -pe 's/([.\^\$*+?()[\]{}\\])/\\$1/g'
        }
        spdx_expression_regex=$(escape_for_regex '${{ inputs.license }}')
        project_name_regex=$(escape_for_regex '${{ inputs.project-name }}')
        header_regex="^// Copyright (19|20)[\d]{2} (.+ and )?the $project_name_regex Authors( and .+)?\$\n^// SPDX-License-Identifier: $spdx_expression_regex\$\n\n"
        echo "Copyright header regex: $header_regex"
        set +e
        output=$(rg "$header_regex" --files-without-match --multiline ${{ inputs.globs }} .)
        set -e

        if [ -n "$output" ]; then
          echo -e "The following files lack the correct copyright header:\n"
          echo $output
          echo -e "\n\nPlease add the following header:\n"
          echo "// Copyright $(date +%Y) the $(echo '${{ inputs.project-name }}') Authors"
          echo '// SPDX-License-Identifier: ${{ inputs.license }}'
          echo -e "\n... rest of the file ...\n"
          exit 1
        fi

        echo "All files have correct copyright headers."
        exit 0
