name: Presence
description: Checks whether debug_assertions is present in Rust code.

outputs:
  debug-assertions:
    value: ${{ steps.debug-assertions.outputs.present }}

runs:
  using: composite
  steps:
    - name: Check for debug_assertions in Rust code
      id: debug-assertions
      shell: bash
      run: |
        # Check for debug_assertions in Rust code
        grep --version
        set +e
        grep -qr --include="*.rs" "debug_assertions" .
        exit_code=$?
        set -e
        if [ $exit_code -eq 0 ]; then
          echo "present=true" >> $GITHUB_OUTPUT
          echo "Found debug_assertions in Rust code."
          exit 0
        elif [ $exit_code -eq 1 ]; then
          echo "present=false" >> $GITHUB_OUTPUT
          echo "Did not find debug_assertions in Rust code."
          exit 0
        else
          echo "Grep ran into trouble and returned an unexpected exit code."
          exit $exit_code
        fi
