name: Presence
description: Checks whether debug_assertions is present in Rust code.

outputs:
  debug-assertions:
    value: ${{ steps.debug-assertions.outputs.present }}

runs:
  using: composite
  steps:
    - name: Install ripgrep
      shell: bash
      run: |
        if command -v rg >/dev/null 2>&1; then
          echo "Found ripgrep already installed."
        else
          echo "Installing ripgrep ..."
          case $RUNNER_OS in
            Windows)
              choco install ripgrep
              ;;
            macOS)
              brew install ripgrep
              ;;
            Linux)
              sudo apt install ripgrep
              ;;
          esac
        fi

   - name: Install ripgrep again
      shell: bash
      run: |
        if command -v rg >/dev/null 2>&1; then
          echo "Found ripgrep already installed."
        else
          echo "Installing ripgrep ..."
          case $RUNNER_OS in
            Windows)
              choco install ripgrep
              ;;
            macOS)
              brew install ripgrep
              ;;
            Linux)
              sudo apt install ripgrep
              ;;
          esac
        fi

    - name: Check for debug_assertions in Rust code
      id: debug-assertions
      shell: bash
      run: |
        rg --version
        set +e
        rg "debug_assertions" -q -g "*.rs" .
        exit_code=$?
        set -e
        if [ $exit_code -eq 0 ]; then
          echo "present=true" >> $GITHUB_OUTPUT
          echo "Found debug_assertions in Rust code."
          exit 0
        else
          echo "present=false" >> $GITHUB_OUTPUT
          echo "Did not find debug_assertions in Rust code."
          exit 0
        fi
