name: Android

on:
  workflow_call:
    inputs:
      # Basic inputs
      target:
        type: string
        required: true
      packages:
        type: string
        required: true
      # Advanced inputs
      names:
        type: string
        required: false
        default: >
          {
            "x86_64-linux-android":       "x64",
            "aarch64-linux-android":      "ARM64",
            "armv7-linux-androideabi":    "ARMv7"
          }
      oses:
        type: string
        required: false
        default: >
          {
            "x86_64-linux-android":       "ubuntu-latest",
            "aarch64-linux-android":      "ubuntu-latest",
            "armv7-linux-androideabi":    "ubuntu-latest"
          }

jobs:
  android:
    name: ${{ fromJson(inputs.names)[inputs.target] }}
    runs-on: ${{ fromJson(inputs.oses)[inputs.target] }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get configuration
        id: config
        uses: xStrom/ci-test/config@main

      - name: Install Rust ${{ steps.config.outputs.rust-stable }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.config.outputs.rust-stable }}
          targets: ${{ inputs.target }}

      - name: Install cargo-apk
        run: cargo install cargo-apk

      - name: Run cargo apk check
        env:
          RUSTFLAGS: -D warnings
        run: cargo apk check ${{ inputs.packages }} --profile ci --target ${{ inputs.target }} --all-features
