env:
  SOMETHING: "awesome"

name: CI

on:
  pull_request:
  merge_group:
  # We run on push, even though the commit is the same as when we ran in merge_group.
  # This allows the cache to be primed.
  # See https://github.com/orgs/community/discussions/66430
  push:
    branches:
      - main

jobs:
  config:
    name: Configuration
    runs-on: ubuntu-latest
    outputs:
      something: ${{ env.SOMETHING }}
    steps:
      - name: Foo
        run: echo Foo

  local-fmt:
    name: Local
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine Rust versions
        id: versions
        uses: xStrom/ci-test/versions@main

      - name: Install Rust ${{ steps.versions.outputs.rust-stable }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.versions.outputs.rust-stable }}
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all --check

  formatting:
    name: Formatting
    uses: xStrom/ci-test/.github/workflows/formatting.yml@main

  typos:
    name: Typos
    uses: xStrom/ci-test/.github/workflows/typos.yml@main

  clippy:
    name: ${{ fromJson('''Clippy''') }}
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc, x86_64-unknown-linux-gnu]
    uses: xStrom/ci-test/.github/workflows/clippy.yml@main
    with:
      target: ${{ matrix.target }}

  android:
    name: ${{ fromJson('''Android''') }}
    strategy:
      matrix:
        target: [aarch64-linux-android]
    uses: xStrom/ci-test/.github/workflows/android.yml@main
    with:
      target: ${{ matrix.target }}
      packages: "-p test"

  msrv:
    name: ${{ fromJson('''MSRV''') }}
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc, aarch64-apple-darwin, x86_64-unknown-linux-gnu]
    uses: xStrom/ci-test/.github/workflows/msrv.yml@main
    with:
      target: ${{ matrix.target }}

  docs:
    name: ${{ fromJson('''Docs''') }}
    strategy:
      matrix:
        target: [x86_64-pc-windows-msvc, aarch64-apple-darwin, x86_64-unknown-linux-gnu]
    uses: xStrom/ci-test/.github/workflows/docs.yml@main
    with:
      target: ${{ matrix.target }}
