env:
  CI_VERSION: "main"

name: CI

on:
  pull_request:
  merge_group:
  # We run on push, even though the commit is the same as when we ran in merge_group.
  # This allows the cache to be primed.
  # See https://github.com/orgs/community/discussions/66430
  push:
    branches:
      - main

jobs:
  config:
    name: Configuration
    runs-on: ubuntu-latest
    outputs:
      ci-version: ${{ env.CI_VERSION }}
    steps:
      - name: Foo
        run: echo Foo

      - name: Create Clippy Proxy
        run: |
          cat <<'EOF' > ./.github/workflows/proxy-clippy.yml
          name: Proxy Clippy Workflow

          on:
            workflow_call:
              inputs:
                target:
                  type: string
                  required: true

          jobs:
            proxy:
              name: 🚀📎
              uses: xStrom/ci-test/.github/workflows/clippy.yml@main
              with:
                target: ${{ inputs.target }}
          EOF

  local-fmt:
    name: local fmt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.83
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all --check

  remote-fmt:
    name: Formatting
    uses: xStrom/ci-test/.github/workflows/formatting.yml@main

  remote-clippy:
    name: "${{ fromJson('''cargo clippy''') }}"
    needs: config
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-pc-windows-msvc]
    uses: .github/workflows/proxy-clippy.yml
    with:
      target: ${{ matrix.target }}
