name: cargo clippy

on:
  workflow_call:
    inputs:
      # Basic inputs
      target:
        type: string
        required: true
      # Advanced inputs
      names:
        type: string
        required: false
        default: >
          {
            "x86_64-unknown-linux-gnu": "Linux",
            "x86_64-pc-windows-msvc":   "Windows"
          }
      oses:
        type: string
        required: false
        default: >
          {
            "x86_64-unknown-linux-gnu": "ubuntu-latest",
            "x86_64-pc-windows-msvc":   "windows-latest"
          }

jobs:
  clippy-stable:
    name: ${{ fromJson(inputs.names)[inputs.target] }}
    runs-on: ${{ fromJson(inputs.oses)[inputs.target] }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine Rust versions
        id: versions
        uses: xStrom/ci-test/versions@main

      - name: Install Rust ${{ steps.versions.outputs.rust-stable }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.versions.outputs.rust-stable }}
          targets: ${{ inputs.target }}
          components: clippy

      - name: Run cargo clippy
        run: cargo clippy --workspace --locked --profile ci --target ${{ inputs.target }} -- -D warnings
