env:
  # We aim to always test with the latest stable Rust toolchain, however we pin to a specific
  # version like 1.70. Note that we only specify MAJOR.MINOR and not PATCH so that bugfixes still
  # come automatically. If the version specified here is no longer the latest stable version,
  # then please feel free to submit a PR that adjusts it along with the potential clippy fixes.
  RUST_STABLE_VER: "1.82" # In quotes because otherwise (e.g.) 1.70 would be interpreted as 1.7

name: cargo clippy

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true

jobs:
  clippy-stable:
    name: ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
#    strategy:
#      matrix:
#        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust ${{ env.RUST_STABLE_VER }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.RUST_STABLE_VER }}
          components: clippy

      - name: Run cargo clippy
        run: cargo clippy --workspace --locked --profile ci -- -D warnings
