name: Documentation

on:
  workflow_call:
    inputs:
      # Basic inputs
      target:
        type: string
        required: true
      exclude:
        type: string
        required: false
        default: ""
      dependencies:
        type: string
        required: false
        default: ""
      env:
        type: string
        required: false
        default: ""
      # Advanced inputs
      names:
        type: string
        required: false
        default: >
          {
            "x86_64-pc-windows-msvc":     "Windows x64",
            "aarch64-pc-windows-msvc":    "Windows ARM64",

            "x86_64-apple-darwin":        "macOS x64",
            "aarch64-apple-darwin":       "macOS ARM64",

            "x86_64-unknown-linux-gnu":   "Linux x64",
            "aarch64-unknown-linux-gnu":  "Linux ARM64",

            "x86_64-linux-android":       "Android x64",
            "aarch64-linux-android":      "Android ARM64",
            "armv7-linux-androideabi":    "Android ARMv7",

            "x86_64-apple-ios":           "iOS x64",
            "aarch64-apple-ios":          "iOS ARM64",

            "wasm32-unknown-unknown":     "Wasm"
          }

jobs:
  doc:
    name: ${{ fromJson(inputs.names)[inputs.target] }}
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Process inputs
        if: inputs.env != '' || inputs.exclude != ''
        uses: xStrom/ci-test/inputs@main
        with:
          env: ${{ inputs.env }}
          exclude: ${{ inputs.exclude }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust nightly
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          targets: ${{ inputs.target }}

      - name: Install additional dependencies
        if: inputs.dependencies != ''
        run: |
          # Install additional dependencies
          ${{ inputs.dependencies }}

      - name: Restore cache
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ inputs.target }}
          save-if: ${{ github.event_name != 'merge_group' }}

      - name: Run cargo doc
        env:
          RUSTDOCFLAGS: --cfg docsrs -D warnings
        run: cargo doc --workspace $EXCLUDE_ARGS --locked --profile ci --target ${{ inputs.target }} --all-features --no-deps --document-private-items -Zunstable-options -Zrustdoc-scrape-examples
