name: Formatting

on:
  workflow_call:
    inputs:
      # Basic inputs
      rdme-projects:
        type: string
        required: false
        default: ""

jobs:
  formatting:
    name: 🔍
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Determine Rust versions
      #   id: versions
      #   uses: xStrom/ci-test/versions@main

      # - name: Install Rust ${{ steps.versions.outputs.rust-stable }}
      #   uses: dtolnay/rust-toolchain@master
      #   with:
      #     toolchain: ${{ steps.versions.outputs.rust-stable }}
      #     components: rustfmt

      # - name: Run cargo fmt
      #   run: cargo fmt --all --check

      #- name: Install ripgrep
      #  run: sudo apt install ripgrep

      - name: Testing presence
        id: presence
        uses: xStrom/ci-test/presence@main

      - name: Presence results
        run: |
          echo "Presence returned for debug_assertions: ${{ steps.presence.outputs.debug-assertions }}"

      # - name: Check copyright headers
      #   run: bash .github/copyright.sh

      # - name: Check debug_assertions presence
      #   run: bash .github/debug_assertions.sh

      # - name: Install cargo-rdme
      #   if: inputs.rdme-projects != ''
      #   uses: taiki-e/install-action@v2
      #   with:
      #     tool: cargo-rdme

      # - name: Run cargo rdme
      #   if: inputs.rdme-projects != ''
      #   run: |
      #     for project in $(echo '${{ inputs.rdme-projects }}' | tr ' ' '\n'); do
      #       echo "Running cargo rdme on $project ..."
      #       cargo rdme --check --heading-base-level=0 --workspace-project=$project
      #     done
      #     echo "All projects are up to date."
