name: Formatting

on:
  workflow_call:
    inputs:
      # Basic inputs
      rdme-projects:
        type: string
        required: false
        default: ""

jobs:
  formatting:
    name: 🔍
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Determine Rust versions
      #   id: versions
      #   uses: xStrom/ci-test/versions@main

      # - name: Install Rust ${{ steps.versions.outputs.rust-stable }}
      #   uses: dtolnay/rust-toolchain@master
      #   with:
      #     toolchain: ${{ steps.versions.outputs.rust-stable }}
      #     components: rustfmt

      # - name: Run cargo fmt
      #   run: cargo fmt --all --check

      # - name: Check copyright headers
      #   uses: xStrom/ci-test/copyright@main
      #   with:
      #     project-name: CI

      # - name: Install cargo-rdme
      #   if: inputs.rdme-projects != ''
      #   uses: taiki-e/install-action@v2
      #   with:
      #     tool: cargo-rdme

      # - name: Run cargo rdme
      #   if: inputs.rdme-projects != ''
      #   run: |
      #     for project in $(echo '${{ inputs.rdme-projects }}' | tr ' ' '\n'); do
      #       echo "Running cargo rdme on $project ..."
      #       cargo rdme --check --heading-base-level=0 --workspace-project=$project
      #     done
      #     echo "All projects are up to date."

      # - name: Install Taplo
      #   uses: uncenter/setup-taplo@09968a8ae38d66ddd3d23802c44bf6122d7aa991 # v1
      #   with:
      #     version: "0.9.3"

      - name: Install Taplo
        run: cargo install taplo-cli --locked

      - name: Run taplo fmt
        run: taplo fmt --check --diff

      # - name: Install Taplo
      #   run: |
      #     eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
      #     brew install taplo
      #     brew info taplo
      #     brew --cellar
      #     brew --cellar taplo
      #     ls -alF /home/linuxbrew/.linuxbrew/Cellar/taplo/0.9.3/bin

      # - name: Run taplo fmt
      #   run: /home/linuxbrew/.linuxbrew/Cellar/taplo/0.9.3/bin/taplo fmt --check --diff
