name: Formatting

on:
  workflow_call:
    inputs:
      # Basic inputs
      taplo:
        description: Whether to run Taplo to check TOML formatting.
        required: false
        type: boolean
        default: true
      rdme-projects:
        description: The project names which should be checked with cargo rdme.
        required: false
        type: string
        default: ""
      copyright-name:
        description: The name in the phrase "the $name Authors".
        required: false
        type: string
        default: ""
      copyright-license:
        description: The SPDX license expression.
        required: false
        type: string
        default: Apache-2.0 OR MIT
      copyright-glob:
        description: The files to include.
        required: false
        type: string
        default: "*.rs"
      # Advanced inputs
      copyright-config:
        # Expected input JSON format:
        # [
        #   {
        #     "name":    "Cool",
        #     "license": "Apache-2.0 OR MIT",
        #     "globs":   ["*.rs", "!other/"]
        #   },
        #   {
        #     "name":    "Cool",
        #     "license": "BSD",
        #     "globs":   ["other/**/*.rs"]
        #   }
        # ]
        description: Advanced configuration in a single JSON array, overrides basic inputs.
        required: false
        type: string
        default: ""

jobs:
  formatting:
    name: Formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Determine Rust versions
        id: versions
        uses: xStrom/ci-test/versions@main

      - name: Install Rust ${{ steps.versions.outputs.rust-stable }}
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ steps.versions.outputs.rust-stable }}
          components: rustfmt

      - name: Run cargo fmt
        run: cargo fmt --all --check

      - name: Check copyright headers
        if: inputs.copyright-name != '' || inputs.copyright-config != ''
        uses: xStrom/ci-test/copyright@main
        with:
          name: ${{ inputs.copyright-name }}
          license: ${{ inputs.copyright-license }}
          glob: ${{ inputs.copyright-glob }}
          config: ${{ inputs.copyright-config }}

      - name: Install Taplo
        if: inputs.taplo
        uses: uncenter/setup-taplo@09968a8ae38d66ddd3d23802c44bf6122d7aa991 # v1.0.8
        with:
          version: "0.9.3"

      - name: Run taplo fmt
        if: inputs.taplo
        run: taplo fmt --check --diff

      - name: Install cargo-rdme
        if: inputs.rdme-projects != ''
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-rdme

      - name: Run cargo rdme
        if: inputs.rdme-projects != ''
        run: |
          for project in $(echo '${{ inputs.rdme-projects }}'); do
            echo "Running cargo rdme on $project ..."
            cargo rdme --check --heading-base-level=0 --workspace-project=$project
          done
          echo "All projects are up to date."
