name: Prime LFS cache

on:
  workflow_call:
    inputs:
      # Basic inputs
      key:
        type: string
        required: false
        default: ""
      key-glob:
        type: string
        required: false
        default: ""
    outputs:
      key:
        value: ${{ jobs.prime-lfs-cache.outputs.key }}

jobs:
  prime-lfs-cache:
    name: LFS cache
    runs-on: ubuntu-latest
    continue-on-error: true
    outputs:
      key: lfs-${{ steps.key.outputs.value }}
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate key
        id: key
        env:
          GLOB_HASH: ${{ hashFiles(inputs.key-glob) }}
        run: |
          # Generate key
          printf "value=%s%s" "${{ inputs.key }}" "$GLOB_HASH" | tee -a $GITHUB_OUTPUT

      - name: Fail on purpose
        run: exit 1

      # - name: Cache git LFS
      #   id: lfs-cache
      #   uses: actions/cache@v4
      #   with:
      #     path: .git/lfs
      #     key: lfs-${{ steps.key.outputs.value }}
      #     restore-keys: lfs-
      #     enableCrossOsArchive: true

      # - name: Fetch LFS data
      #   if: ${{ steps.lfs-cache.outputs.cache-hit != 'true' }}
      #   run: git lfs fetch
