name: Proxy Workflow

on:
  workflow_call:
    inputs:
      target:
        type: string
        required: true

jobs:
  proxy:
    name: 🤡📎
    uses: ./.github/workflows/proxy-clippy.yml
    with:
      target: ${{ inputs.target }}
