name: Proxy Workflow

on:
  workflow_call:
    inputs:
      target:
        type: string
        required: true

jobs:
  proxy:
    name: 📎
    uses: xStrom/ci-test/.github/workflows/clippy.yml@main
    with:
      target: ${{ inputs.target }}
