name: Typos

on:
  workflow_call:
    inputs:
      # Basic inputs
      env:
        type: string
        required: false
        default: ""

jobs:
  typos:
    name: Typos
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    steps:
      - name: Process inputs
        if: inputs.env != ''
        uses: xStrom/ci-test/inputs@main
        with:
          env: ${{ inputs.env }}

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check typos
        uses: crate-ci/typos@v1.28.2
