name: Typos

on:
  workflow_call:

jobs:
  formatting:
    name: Typos
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check typos
        uses: crate-ci/typos@v1.28.2
