name: Typos

on:
  workflow_call:

jobs:
  formatting:
    name: 📜
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check typos
        uses: crate-ci/typos@v1.28.2

      - name: Suggest actions to handle failure
        if: failure()
        run: |
          # Suggest actions to handle failure
          yellow="\e[33m"
          cend="\e[0m"
          printf "${yellow}Consider changing the text that failed the typos check, or if you think it's not a typo then modify .typos.toml.${cend}\n"
          exit 1
